global:
  scrape_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets: 
      - 'alertmanager:9093'

rule_files:
  - "prometheus_rules.yml"

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']