groups:
  - name: otel-alerts
    rules:
      - alert: OTelErrorTraceDetected
        expr: increase(otelcol_exporter_sent_spans{exporter="jaeger"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Error traces detected in OpenTelemetry Collector"
          description: "Prometheus has detected error traces in the OpenTelemetry Collector over the past 5 minutes."
